### ISSUE TITLE
Add option for external auth

### ISSUE THREAD

**Issue by ovniroto** [openhotel/openhotel#169]
It would be nice to have an option to allow external authentication. I add some points that could serve as an example of how it could work.

- When enabling external authentication, the hotel would not show the login
- The hotel would be responsible for checking if the client has the session active
- The hotel should redirect to the external login URL in case of no active session
- When enabling external authentication, there should be a configuration option to add the redirection URL for the external login

**Comment by pagoru** [comment]
Implement OHAP https://github.com/openhotel/auth/issues/38
